[package]
name = "peerchat-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.101", features = ["full"] }
quote = "1.0.21"
darling = "0.14.1"
proc-macro2 = "1.0.46"
